#!$PREFIX/bin/bash

if [ ! -d ~/storage ];
then
    termux-setup-storage
fi

sleep 5

pkg install php-apache php-fpm php-sodium -y

rm -f $PREFIX/etc/apache2/httpd.conf

cp httpd.conf $PREFIX/etc/apache2/

rm -f $PREFIX/etc/apache2/extra/httpd-ssl.conf

cp httpd-ssl.conf $PREFIX/etc/apache2/extra/

pkg install openssl-tool -y

openssl req \
    -x509 \
    -newkey rsa:2048 \
    -keyout server.key \
    -out server.crt \
    -days 365 \
    -nodes \
    -subj '/CN=localhost'

mv -f server.crt $PREFIX/etc/apache2/
mv -f server.key $PREFIX/etc/apache2/

rm -f $PREFIX/bin/matrix

chmod +x matrix

cp matrix $PREFIX/bin/

pkg install mariadb composer -y

mkdir -p /sdcard/htdocs

cp -n .htaccess /sdcard/htdocs/

php_info='/sdcard/htdocs/phpinfo'

if [ ! -d "$php_info" ];
then
    mkdir "$php_info"
    echo "<?php phpinfo(); ?>" > "$php_info/index.php"
fi

if [ ! -d /sdcard/htdocs/phpmyadmin ];
then
    cd /sdcard/htdocs
    composer create-project phpmyadmin/phpmyadmin
fi

cd ~/matrix

cp -f config.inc.php /sdcard/htdocs/phpmyadmin/config.inc.php

YELLOW='\033[0;33m'
NC='\033[0m'

echo "Matrix Server se ha instalado correctamente."
echo "/sdcard/htdocs - es tu directorio de documentos."
echo "Coloca tus archivos en /sdcard/htdocs"
echo -e "Ejecuta: ${YELLOW}matrix start${NC}"